/*
 * Autogenerated from DBus interface definitions, do not modify this file,
 * instead modify your interface source code (xml or vala)
 */
import { type SignalSpec } from '@wakit/companion'

declare global
{

  namespace bridge
    {

      /**
       * name: org.hck.wakit.Example.Interface
       */
      namespace WakitExampleInterface
        {

          function AlwaysReturns (value: string): Promise<string>;
          function AlwaysThrows (value: string): Promise<string>;
          function EmitSignal1 (value: string): Promise<void>;
          function RandomNumbers (): Promise<Uint32Array>;
          function RandomUUID (): Promise<string>;
          function RandomUUIDs (): Promise<string[]>;

          let Store: string;

          function disconnect (signal_id: number): void;

          const Signal1: SignalSpec<[string]>;
        }
    }
}

export { }
